[package]
name = "v8_derive"
version = "0.4.0"
edition = "2021"
description = "Derive macros and helpers for Rusty v8"
repository = "https://github.com/mibes404/v8_derive.git"
license = "MIT"

[dependencies]
serde_json = { version = "1.0.149", optional = true }
thiserror = "2.0.18"
v8 = "150.2.0"
v8_derive_macros = { path = "../v8_derive_macros", version = "0.4.0" }

[features]
default = []
json = ["serde_json"]
